//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.20 at 04:32:23 PM ICT 
//


package vn.mobifone.ocsplatform;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sessionIdKeep" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionIdKeep"
})
@XmlRootElement(name = "KeepAliveRequest")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
public class KeepAliveRequest {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    protected String sessionIdKeep;

    /**
     * Gets the value of the sessionIdKeep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public String getSessionIdKeep() {
        return sessionIdKeep;
    }

    /**
     * Sets the value of the sessionIdKeep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public void setSessionIdKeep(String value) {
        this.sessionIdKeep = value;
    }

}
