//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.14 at 05:10:13 PM ICT 
//


package vn.mobifone.ocsplatform;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn.mobifone.ocsplatform package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn.mobifone.ocsplatform
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExecuteTaskReq }
     * 
     */
    public ExecuteTaskReq createExecuteTaskReq() {
        return new ExecuteTaskReq();
    }

    /**
     * Create an instance of {@link ExecuteTaskRes }
     * 
     */
    public ExecuteTaskRes createExecuteTaskRes() {
        return new ExecuteTaskRes();
    }

    /**
     * Create an instance of {@link KeepAliveReq }
     * 
     */
    public KeepAliveReq createKeepAliveReq() {
        return new KeepAliveReq();
    }

    /**
     * Create an instance of {@link KeepAliveRes }
     * 
     */
    public KeepAliveRes createKeepAliveRes() {
        return new KeepAliveRes();
    }

    /**
     * Create an instance of {@link LoginReq }
     * 
     */
    public LoginReq createLoginReq() {
        return new LoginReq();
    }

    /**
     * Create an instance of {@link LoginRes }
     * 
     */
    public LoginRes createLoginRes() {
        return new LoginRes();
    }

}
