//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.20 at 11:58:51 AM ICT 
//


package vn.mobifone.ocsplatform;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn.mobifone.ocsplatform package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn.mobifone.ocsplatform
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RetrieveRequest }
     * 
     */
    public RetrieveRequest createRetrieveRequest() {
        return new RetrieveRequest();
    }

    /**
     * Create an instance of {@link RetrieveResponse }
     * 
     */
    public RetrieveResponse createRetrieveResponse() {
        return new RetrieveResponse();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList }
     * 
     */
    public RetrieveResponse.TaskResponseList createRetrieveResponseTaskResponseList() {
        return new RetrieveResponse.TaskResponseList();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList.TaskResponse }
     * 
     */
    public RetrieveResponse.TaskResponseList.TaskResponse createRetrieveResponseTaskResponseListTaskResponse() {
        return new RetrieveResponse.TaskResponseList.TaskResponse();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList }
     * 
     */
    public RetrieveResponse.TaskResponseList.TaskResponse.CollectionList createRetrieveResponseTaskResponseListTaskResponseCollectionList() {
        return new RetrieveResponse.TaskResponseList.TaskResponse.CollectionList();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection }
     * 
     */
    public RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection createRetrieveResponseTaskResponseListTaskResponseCollectionListCollection() {
        return new RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList }
     * 
     */
    public RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList createRetrieveResponseTaskResponseListTaskResponseCollectionListCollectionRecordList() {
        return new RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList }
     * 
     */
    public RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList createRetrieveResponseTaskResponseListTaskResponseCollectionListCollectionRecordListParamList() {
        return new RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList();
    }

    /**
     * Create an instance of {@link RetrieveRequest.TaskList }
     * 
     */
    public RetrieveRequest.TaskList createRetrieveRequestTaskList() {
        return new RetrieveRequest.TaskList();
    }

    /**
     * Create an instance of {@link RetrieveRequest.TaskList.Task }
     * 
     */
    public RetrieveRequest.TaskList.Task createRetrieveRequestTaskListTask() {
        return new RetrieveRequest.TaskList.Task();
    }

    /**
     * Create an instance of {@link RetrieveRequest.TaskList.Task.QueryCriteria }
     * 
     */
    public RetrieveRequest.TaskList.Task.QueryCriteria createRetrieveRequestTaskListTaskQueryCriteria() {
        return new RetrieveRequest.TaskList.Task.QueryCriteria();
    }

    /**
     * Create an instance of {@link RetrieveRequest.SessionInfo }
     * 
     */
    public RetrieveRequest.SessionInfo createRetrieveRequestSessionInfo() {
        return new RetrieveRequest.SessionInfo();
    }

    /**
     * Create an instance of {@link RetrieveRequest.RequestInfo }
     * 
     */
    public RetrieveRequest.RequestInfo createRetrieveRequestRequestInfo() {
        return new RetrieveRequest.RequestInfo();
    }

    /**
     * Create an instance of {@link RetrieveRequest.NERoutingInfo }
     * 
     */
    public RetrieveRequest.NERoutingInfo createRetrieveRequestNERoutingInfo() {
        return new RetrieveRequest.NERoutingInfo();
    }

    /**
     * Create an instance of {@link RetrieveResponse.RequestInfo }
     * 
     */
    public RetrieveResponse.RequestInfo createRetrieveResponseRequestInfo() {
        return new RetrieveResponse.RequestInfo();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo }
     * 
     */
    public RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo createRetrieveResponseTaskResponseListTaskResponseErrorInfo() {
        return new RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo();
    }

    /**
     * Create an instance of {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList.Param }
     * 
     */
    public RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList.Param createRetrieveResponseTaskResponseListTaskResponseCollectionListCollectionRecordListParamListParam() {
        return new RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList.Param();
    }

    /**
     * Create an instance of {@link RetrieveRequest.TaskList.Task.QueryCriteria.Param }
     * 
     */
    public RetrieveRequest.TaskList.Task.QueryCriteria.Param createRetrieveRequestTaskListTaskQueryCriteriaParam() {
        return new RetrieveRequest.TaskList.Task.QueryCriteria.Param();
    }

}
