//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.20 at 04:32:23 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://alcatel-lucent.com/esm/ws/svcmgr/V2_0")
package vn.mobifone.ocsplatform;
