//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.20 at 11:58:51 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://alcatel-lucent.com/esm/ws/svcmgr/V2_0",
        elementFormDefault = XmlNsForm.QUALIFIED,
        xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://alcatel-lucent.com/esm/ws/svcmgr/V2_0", prefix = ""),
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://schemas.xmlsoap.org/soap/envelope/", prefix = "S")})
package vn.mobifone.ocsplatform;

import javax.xml.bind.annotation.XmlNsForm;
