//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.14 at 05:10:13 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ocsplatform.mobifone.vn")
package vn.mobifone.ocsplatform;
