//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.20 at 04:32:23 PM ICT 
//


package vn.mobifone.ocsplatform;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestInfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ReqID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TaskResponseList"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TaskResponse" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ErrorInfo"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="ErrorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="ErrorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="CollectionList"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Collection" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="CollectionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="RecordList"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="ParamList" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                                             &lt;complexType&gt;
 *                                                               &lt;complexContent&gt;
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                   &lt;sequence&gt;
 *                                                                     &lt;element name="Param" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                                                       &lt;complexType&gt;
 *                                                                         &lt;complexContent&gt;
 *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                             &lt;sequence&gt;
 *                                                                               &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                                               &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                                             &lt;/sequence&gt;
 *                                                                           &lt;/restriction&gt;
 *                                                                         &lt;/complexContent&gt;
 *                                                                       &lt;/complexType&gt;
 *                                                                     &lt;/element&gt;
 *                                                                   &lt;/sequence&gt;
 *                                                                 &lt;/restriction&gt;
 *                                                               &lt;/complexContent&gt;
 *                                                             &lt;/complexType&gt;
 *                                                           &lt;/element&gt;
 *                                                         &lt;/sequence&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestInfo",
    "result",
    "taskResponseList"
})
@XmlRootElement(name = "RetrieveResponse")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
public class RetrieveResponse {

    @XmlElement(name = "RequestInfo", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    protected RetrieveResponse.RequestInfo requestInfo;
    @XmlElement(name = "Result", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    protected String result;
    @XmlElement(name = "TaskResponseList", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    protected RetrieveResponse.TaskResponseList taskResponseList;

    /**
     * Gets the value of the requestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RetrieveResponse.RequestInfo }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public RetrieveResponse.RequestInfo getRequestInfo() {
        return requestInfo;
    }

    /**
     * Sets the value of the requestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetrieveResponse.RequestInfo }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public void setRequestInfo(RetrieveResponse.RequestInfo value) {
        this.requestInfo = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the taskResponseList property.
     * 
     * @return
     *     possible object is
     *     {@link RetrieveResponse.TaskResponseList }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public RetrieveResponse.TaskResponseList getTaskResponseList() {
        return taskResponseList;
    }

    /**
     * Sets the value of the taskResponseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetrieveResponse.TaskResponseList }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public void setTaskResponseList(RetrieveResponse.TaskResponseList value) {
        this.taskResponseList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ReqID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reqID"
    })
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public static class RequestInfo {

        @XmlElement(name = "ReqID", required = true)
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
        protected String reqID;

        /**
         * Gets the value of the reqID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
        public String getReqID() {
            return reqID;
        }

        /**
         * Sets the value of the reqID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
        public void setReqID(String value) {
            this.reqID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TaskResponse" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ErrorInfo"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="ErrorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="ErrorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="CollectionList"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Collection" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="CollectionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="RecordList"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="ParamList" maxOccurs="unbounded" minOccurs="0"&gt;
     *                                                   &lt;complexType&gt;
     *                                                     &lt;complexContent&gt;
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                         &lt;sequence&gt;
     *                                                           &lt;element name="Param" maxOccurs="unbounded" minOccurs="0"&gt;
     *                                                             &lt;complexType&gt;
     *                                                               &lt;complexContent&gt;
     *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                                   &lt;sequence&gt;
     *                                                                     &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                                     &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                                   &lt;/sequence&gt;
     *                                                                 &lt;/restriction&gt;
     *                                                               &lt;/complexContent&gt;
     *                                                             &lt;/complexType&gt;
     *                                                           &lt;/element&gt;
     *                                                         &lt;/sequence&gt;
     *                                                       &lt;/restriction&gt;
     *                                                     &lt;/complexContent&gt;
     *                                                   &lt;/complexType&gt;
     *                                                 &lt;/element&gt;
     *                                               &lt;/sequence&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taskResponse"
    })
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
    public static class TaskResponseList {

        @XmlElement(name = "TaskResponse")
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
        protected List<RetrieveResponse.TaskResponseList.TaskResponse> taskResponse;

        /**
         * Gets the value of the taskResponse property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taskResponse property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaskResponse().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RetrieveResponse.TaskResponseList.TaskResponse }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
        public List<RetrieveResponse.TaskResponseList.TaskResponse> getTaskResponse() {
            if (taskResponse == null) {
                taskResponse = new ArrayList<RetrieveResponse.TaskResponseList.TaskResponse>();
            }
            return this.taskResponse;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ErrorInfo"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="ErrorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="ErrorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="CollectionList"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Collection" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="CollectionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="RecordList"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="ParamList" maxOccurs="unbounded" minOccurs="0"&gt;
         *                                         &lt;complexType&gt;
         *                                           &lt;complexContent&gt;
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                               &lt;sequence&gt;
         *                                                 &lt;element name="Param" maxOccurs="unbounded" minOccurs="0"&gt;
         *                                                   &lt;complexType&gt;
         *                                                     &lt;complexContent&gt;
         *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                                         &lt;sequence&gt;
         *                                                           &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                                           &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                                         &lt;/sequence&gt;
         *                                                       &lt;/restriction&gt;
         *                                                     &lt;/complexContent&gt;
         *                                                   &lt;/complexType&gt;
         *                                                 &lt;/element&gt;
         *                                               &lt;/sequence&gt;
         *                                             &lt;/restriction&gt;
         *                                           &lt;/complexContent&gt;
         *                                         &lt;/complexType&gt;
         *                                       &lt;/element&gt;
         *                                     &lt;/sequence&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "result",
            "errorInfo",
            "collectionList"
        })
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
        public static class TaskResponse {

            @XmlElement(name = "Name", required = true)
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            protected String name;
            @XmlElement(name = "Result", required = true)
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            protected String result;
            @XmlElement(name = "ErrorInfo", required = true)
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            protected RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo errorInfo;
            @XmlElement(name = "CollectionList", required = true)
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            protected RetrieveResponse.TaskResponseList.TaskResponse.CollectionList collectionList;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the result property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public String getResult() {
                return result;
            }

            /**
             * Sets the value of the result property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public void setResult(String value) {
                this.result = value;
            }

            /**
             * Gets the value of the errorInfo property.
             * 
             * @return
             *     possible object is
             *     {@link RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo getErrorInfo() {
                return errorInfo;
            }

            /**
             * Sets the value of the errorInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public void setErrorInfo(RetrieveResponse.TaskResponseList.TaskResponse.ErrorInfo value) {
                this.errorInfo = value;
            }

            /**
             * Gets the value of the collectionList property.
             * 
             * @return
             *     possible object is
             *     {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public RetrieveResponse.TaskResponseList.TaskResponse.CollectionList getCollectionList() {
                return collectionList;
            }

            /**
             * Sets the value of the collectionList property.
             * 
             * @param value
             *     allowed object is
             *     {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList }
             *     
             */
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public void setCollectionList(RetrieveResponse.TaskResponseList.TaskResponse.CollectionList value) {
                this.collectionList = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Collection" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="CollectionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="RecordList"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="ParamList" maxOccurs="unbounded" minOccurs="0"&gt;
             *                               &lt;complexType&gt;
             *                                 &lt;complexContent&gt;
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                     &lt;sequence&gt;
             *                                       &lt;element name="Param" maxOccurs="unbounded" minOccurs="0"&gt;
             *                                         &lt;complexType&gt;
             *                                           &lt;complexContent&gt;
             *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                               &lt;sequence&gt;
             *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                                                 &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                                               &lt;/sequence&gt;
             *                                             &lt;/restriction&gt;
             *                                           &lt;/complexContent&gt;
             *                                         &lt;/complexType&gt;
             *                                       &lt;/element&gt;
             *                                     &lt;/sequence&gt;
             *                                   &lt;/restriction&gt;
             *                                 &lt;/complexContent&gt;
             *                               &lt;/complexType&gt;
             *                             &lt;/element&gt;
             *                           &lt;/sequence&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "collection"
            })
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public static class CollectionList {

                @XmlElement(name = "Collection")
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                protected List<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection> collection;

                /**
                 * Gets the value of the collection property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the collection property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCollection().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection }
                 * 
                 * 
                 */
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public List<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection> getCollection() {
                    if (collection == null) {
                        collection = new ArrayList<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection>();
                    }
                    return this.collection;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="CollectionName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="RecordList"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="ParamList" maxOccurs="unbounded" minOccurs="0"&gt;
                 *                     &lt;complexType&gt;
                 *                       &lt;complexContent&gt;
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                           &lt;sequence&gt;
                 *                             &lt;element name="Param" maxOccurs="unbounded" minOccurs="0"&gt;
                 *                               &lt;complexType&gt;
                 *                                 &lt;complexContent&gt;
                 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                                     &lt;sequence&gt;
                 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                                       &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                                     &lt;/sequence&gt;
                 *                                   &lt;/restriction&gt;
                 *                                 &lt;/complexContent&gt;
                 *                               &lt;/complexType&gt;
                 *                             &lt;/element&gt;
                 *                           &lt;/sequence&gt;
                 *                         &lt;/restriction&gt;
                 *                       &lt;/complexContent&gt;
                 *                     &lt;/complexType&gt;
                 *                   &lt;/element&gt;
                 *                 &lt;/sequence&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "collectionName",
                    "recordList"
                })
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public static class Collection {

                    @XmlElement(name = "CollectionName", required = true)
                    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                    protected String collectionName;
                    @XmlElement(name = "RecordList", required = true)
                    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                    protected RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList recordList;

                    /**
                     * Gets the value of the collectionName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                    public String getCollectionName() {
                        return collectionName;
                    }

                    /**
                     * Sets the value of the collectionName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                    public void setCollectionName(String value) {
                        this.collectionName = value;
                    }

                    /**
                     * Gets the value of the recordList property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList }
                     *     
                     */
                    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                    public RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList getRecordList() {
                        return recordList;
                    }

                    /**
                     * Sets the value of the recordList property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList }
                     *     
                     */
                    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                    public void setRecordList(RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList value) {
                        this.recordList = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="ParamList" maxOccurs="unbounded" minOccurs="0"&gt;
                     *           &lt;complexType&gt;
                     *             &lt;complexContent&gt;
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                 &lt;sequence&gt;
                     *                   &lt;element name="Param" maxOccurs="unbounded" minOccurs="0"&gt;
                     *                     &lt;complexType&gt;
                     *                       &lt;complexContent&gt;
                     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                           &lt;sequence&gt;
                     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *                           &lt;/sequence&gt;
                     *                         &lt;/restriction&gt;
                     *                       &lt;/complexContent&gt;
                     *                     &lt;/complexType&gt;
                     *                   &lt;/element&gt;
                     *                 &lt;/sequence&gt;
                     *               &lt;/restriction&gt;
                     *             &lt;/complexContent&gt;
                     *           &lt;/complexType&gt;
                     *         &lt;/element&gt;
                     *       &lt;/sequence&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "paramList"
                    })
                    @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                    public static class RecordList {

                        @XmlElement(name = "ParamList")
                        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                        protected List<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList> paramList;

                        /**
                         * Gets the value of the paramList property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the paramList property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getParamList().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList }
                         * 
                         * 
                         */
                        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                        public List<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList> getParamList() {
                            if (paramList == null) {
                                paramList = new ArrayList<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList>();
                            }
                            return this.paramList;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType&gt;
                         *   &lt;complexContent&gt;
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *       &lt;sequence&gt;
                         *         &lt;element name="Param" maxOccurs="unbounded" minOccurs="0"&gt;
                         *           &lt;complexType&gt;
                         *             &lt;complexContent&gt;
                         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *                 &lt;sequence&gt;
                         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                         *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                         *                 &lt;/sequence&gt;
                         *               &lt;/restriction&gt;
                         *             &lt;/complexContent&gt;
                         *           &lt;/complexType&gt;
                         *         &lt;/element&gt;
                         *       &lt;/sequence&gt;
                         *     &lt;/restriction&gt;
                         *   &lt;/complexContent&gt;
                         * &lt;/complexType&gt;
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "param"
                        })
                        @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                        public static class ParamList {

                            @XmlElement(name = "Param")
                            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                            protected List<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList.Param> param;

                            /**
                             * Gets the value of the param property.
                             * 
                             * <p>
                             * This accessor method returns a reference to the live list,
                             * not a snapshot. Therefore any modification you make to the
                             * returned list will be present inside the JAXB object.
                             * This is why there is not a <CODE>set</CODE> method for the param property.
                             * 
                             * <p>
                             * For example, to add a new item, do as follows:
                             * <pre>
                             *    getParam().add(newItem);
                             * </pre>
                             * 
                             * 
                             * <p>
                             * Objects of the following type(s) are allowed in the list
                             * {@link RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList.Param }
                             * 
                             * 
                             */
                            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                            public List<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList.Param> getParam() {
                                if (param == null) {
                                    param = new ArrayList<RetrieveResponse.TaskResponseList.TaskResponse.CollectionList.Collection.RecordList.ParamList.Param>();
                                }
                                return this.param;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType&gt;
                             *   &lt;complexContent&gt;
                             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                             *       &lt;sequence&gt;
                             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                             *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                             *       &lt;/sequence&gt;
                             *     &lt;/restriction&gt;
                             *   &lt;/complexContent&gt;
                             * &lt;/complexType&gt;
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "name",
                                "value"
                            })
                            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                            public static class Param {

                                @XmlElement(name = "Name", required = true)
                                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                                protected String name;
                                @XmlElement(name = "Value", required = true)
                                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                                protected String value;

                                /**
                                 * Gets the value of the name property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                                public String getName() {
                                    return name;
                                }

                                /**
                                 * Sets the value of the name property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                                public void setName(String value) {
                                    this.name = value;
                                }

                                /**
                                 * Gets the value of the value property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                                public String getValue() {
                                    return value;
                                }

                                /**
                                 * Sets the value of the value property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                                public void setValue(String value) {
                                    this.value = value;
                                }

                            }

                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="ErrorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="ErrorCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "errorCode",
                "errorMsg",
                "errorCategory"
            })
            @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
            public static class ErrorInfo {

                @XmlElement(name = "ErrorCode")
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                protected int errorCode;
                @XmlElement(name = "ErrorMsg", required = true)
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                protected String errorMsg;
                @XmlElement(name = "ErrorCategory", required = true)
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                protected String errorCategory;

                /**
                 * Gets the value of the errorCode property.
                 * 
                 */
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public int getErrorCode() {
                    return errorCode;
                }

                /**
                 * Sets the value of the errorCode property.
                 * 
                 */
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public void setErrorCode(int value) {
                    this.errorCode = value;
                }

                /**
                 * Gets the value of the errorMsg property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public String getErrorMsg() {
                    return errorMsg;
                }

                /**
                 * Sets the value of the errorMsg property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public void setErrorMsg(String value) {
                    this.errorMsg = value;
                }

                /**
                 * Gets the value of the errorCategory property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public String getErrorCategory() {
                    return errorCategory;
                }

                /**
                 * Sets the value of the errorCategory property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.xjc.Driver", date = "2021-05-20T04:32:23+07:00", comments = "JAXB RI v2.3.2")
                public void setErrorCategory(String value) {
                    this.errorCategory = value;
                }

            }

        }

    }

}
